title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://spacepenguin1994.github.io/classexample

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/spacepenguin1994/classexample
